#!/usr/bin/env bash
#
# Summary: Starts development in a project
#
# Usage: {cmd} <url>
#
# Clone a project locally and start a development session for it.

set -e

url="$1"

if [ -z "$url" ]; then
  dev help start
fi

# Get project name by removing the github.com URL prefix
project="${url#"https://github.com/"}"

# Extract scope from project (organization or username)
scope="${project%/*}"

# Extract name from project
name="${project#*/}"

# Change into workspace
cd "$WORKSPACE"

# Clone the project if it doesn't exist
if [ ! -e "$scope/$name" ]
then
  # Change into scope directory, creating if necessary
  mkdir -p "$scope"
  cd "$scope"

  gh repo clone "$url"
fi

# Open the project for development
dev pj open "$project"
